version: '3.8'

services:
  mysqlservice:
    image: mysql:8.0
    restart: none
    environment:
      MYSQL_DATABASE: stock_service
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  confirmation-service:
    build: ./confirmation-service
    ports:
      - "4000:4000"

  order-service:
    build: ./order-service
    ports:
      - "6010:6010"
    depends_on:
      - mysqlservice
      - confirmation-service