version: '3.8'

services:
  mysqlservice:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: stock_service
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  confirmation-service:
    image: unlimitedpm/confirmation-service:latest
    ports:
      - "4000:4000"
    deploy:
      replicas: 2

  orderservice:
    image: unlimitedpm/orderservice:latest
    ports:
      - "6010:6010"
    deploy:
      replicas: 2